const featuredGamesData = {
  featuredGames: [
    {
      "id":1,
      "name":"Gta 5 / Grand Theft Auto 5",
      "image":"https://media-rockstargames-com.akamaized.net/rockstargames-newsite/img/global/games/fob/640/V.jpg",
      "secondImage": "https://media-rockstargames-com.akamaized.net/tina-uploads/tina-modules/gta-v/9ca23774eb886a9dce533874723e35ce7a825f5d.png",
      "title":"Welcome To Los Santos",
      "description":"When a young street hustler, a retired bank robber, and a terrifying psychopath find themselves entangled with some of the most frightening and deranged elements of the criminal underworld, the U.S. government, and the entertainment industry, they must pull off a series of dangerous heists to survive in a ruthless city in which they can trust nobody — least of all each other.",
      "screens":"https://media.rockstargames.com/rockstargames/img/global/news/upload/13_gtavpc_03272015.jpg",
      "screens2":"https://images4.alphacoders.com/587/587526.jpg",
      "screens3":"https://cdn.wallpapersafari.com/74/25/Ssbx2Z.jpg",
      "screens4":"https://images2.alphacoders.com/564/564929.jpg",
      "screens5":"https://w0.peakpx.com/wallpaper/519/175/HD-wallpaper-grand-theft-auto-5-open-world-rockstar-games-video-game-game-gta-v-grand-theft-auto-v-gaming-gta-5-gta.jpg",
      "screens6":"https://wallpapermemory.com/uploads/406/grand-theft-auto-v-gta-5-wallpaper-hd-1366x768-195206.jpg",
    },
    {
      "id":2,
      "name":"Gta Online / Grand Theft Auto Online / Gta 5 Online / Grand Theft Auto 5 Online",
      "image":"https://media-rockstargames-com.akamaized.net/rockstargames-newsite/img/global/games/fob/640/GTAOnline.jpg",
      "secondImage":"https://media-rockstargames-com.akamaized.net/tina-uploads/tina-modules/gta-v/224f9a314a45e5828e9af56153f8871c06290689.png",
      "title":"Grand Theft Auto Online ",
      "description":"Experience GTA Online, a dynamic and ever-evolving online universe for up to 30 players, where you can rise from street-level hustler to become a kingpin of your own criminal empire. Enjoy new high-performance vehicle upgrades and improvements like the Career Builder as well as all GTA Online gameplay upgrades, expansions, and content released since launch, ready to enjoy solo or with friends. Pull off daring co-operative Heists, enter adrenaline-fueled Stunt Races, compete in unique Adversary Modes, or hang out in social spaces including nightclubs, arcades, penthouse parties, car meetups, and much more. ",
      "screens":"https://www.cnet.com/a/img/resize/d74e148e124f0b63da3d8322401ee8dbd4a7c3ec/hub/2015/05/18/1e9595f6-8564-4bbe-986c-d7f551896893/gta-v-online-heists.jpg?auto=webp&fit=crop&height=675&width=1200",
      "screens2":"https://sm.ign.com/t/ign_tr/articlepage/g/gta-5-online-heists-hands-on-theyre-real-and-theyr/gta-5-online-heists-hands-on-theyre-real-and-theyr_f6r7.1280.jpg",
      "screens3":"https://i.kinja-img.com/image/upload/c_fit,q_60,w_645/b8af477bc10309189eda4edb777eb674.jpg",
      "screens4":"https://ichef.bbci.co.uk/news/976/cpsprodpb/11916/production/_110285917_weibo.jpg",
      "screens5":"https://cdn.vox-cdn.com/thumbor/HrH3z876S6DzU4MvZWcdCuSxv9A=/0x0:3840x2160/1200x0/filters:focal(0x0:3840x2160):no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/23986305/b9539d138120b49cab5ba58ecce02daf1bba3cdd.jpg",
      "screens6":"https://www.drifted.com/wp-content/uploads/2020/03/featuredimage-flying-cars-supercars-gta-v-fastest-car-in-gta-5.jpg",
    },
    {
      "id":3,
      "name":"Red Dead Redemption 2",
      "image":"https://media-rockstargames-com.akamaized.net/rockstargames-newsite/img/global/games/fob/640/reddeadredemption2.jpg",
      "secondImage":"https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/d6a964da-f73f-431c-a95b-3d4477268790/ddhljyu-7ae3cfb8-17aa-48d1-b15b-d8717fb12903.png/v1/fill/w_1600,h_900,q_80,strp/red_dead_redemption_2___wallpaper_v_2_by_3demerzel_ddhljyu-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9OTAwIiwicGF0aCI6IlwvZlwvZDZhOTY0ZGEtZjczZi00MzFjLWE5NWItM2Q0NDc3MjY4NzkwXC9kZGhsanl1LTdhZTNjZmI4LTE3YWEtNDhkMS1iMTViLWQ4NzE3ZmIxMjkwMy5wbmciLCJ3aWR0aCI6Ijw9MTYwMCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.KvQRIwLsMo5itgm0E24LBjF7-qoRFGVrRWYjD6XRwP4",
      "title":"Red Dead Redemption 2",
      "description":"America, 1899. The end of the Wild West era has begun as lawmen hunt down the last remaining outlaw gangs. Those who will not surrender or succumb are killed. After a robbery goes terribly wrong in the western town of Blackwater, Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal, and fight their way across the rugged heartland of America in order to survive. As deepening internal divisions threaten to tear the gang apart, Arthur must make a choice between his own ideals and loyalty to the gang who raised him.",
      "screens":"https://www.digitaltrends.com/wp-content/uploads/2018/10/red-dead-redemption-2-review-feature-header.jpg?p=1",
      "screens2":"https://media.gq-magazine.co.uk/photos/5d13a9f17fcc8e449d8211f2/16:9/w_2560%2Cc_limit/red-dead-redemption-02-22oct18_b.jpg",
      "screens3":"https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2018/10/red-dead-redemption-2_3.jpg?tf=3840x",
      "screens4":"https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2019/10/red-dead-redemption-2_7.jpg?tf=1920x",
      "screens5":"https://www.pcworld.com/wp-content/uploads/2023/04/base-profile-screenshot-2019.11.05-14.21.01.04-100816901-orig.jpg?resize=1536%2C877&quality=50&strip=all",
      "screens6":"https://variety.com/wp-content/uploads/2018/10/red-dead-redemption-23.jpg?w=1000&h=563&crop=1&resize=910%2C511",
    },
    {
      "id":4,
      "name":"Red Dead Online",
      "image":"https://media-rockstargames-com.akamaized.net/rockstargames-newsite/img/global/games/fob/640/reddeadonline.jpg",
      "secondImage":"https://assets1.ignimgs.com/thumbs/userUploaded/2019/6/7/reddeadonlineblogroll-1559878595973.jpg",
      "title":"Red Dead Online",
      "description":"",
      "screens":"https://www.gameshub.com/wp-content/uploads/sites/5/2022/07/red-dead-online-game.jpeg",
      "screens2":"https://ftw.usatoday.com/wp-content/uploads/sites/90/2022/01/RDO_Screenshot_116_tif_jpgcopy.jpg?w=1000&h=600&crop=1",
      "screens3":"https://cdn.vox-cdn.com/thumbor/L8tbjjPo7mEwqUPg-74hay2ipHw=/0x0:1920x1080/1200x800/filters:focal(859x73:1165x379)/cdn.vox-cdn.com/uploads/chorus_image/image/68632553/71ecad1bc5b48fe3ac76eaea88a18e13e36e8600.0.jpg",
      "screens4":"https://cdn.akamai.steamstatic.com/steam/apps/1404210/ss_74cfc4262102e698745e7004fe7726f59f67c3eb.1920x1080.jpg?t=1656615218",
      "screens5":"https://assetsio.reedpopcdn.com/Red-Dead-Online-%E2%80%93-Community-Update-%E2%80%93-7-7-2022-%E2%80%93-Image-1.jpg?width=1600&height=900&fit=crop&quality=100&format=png&enable=upscale&auto=webp",
      "screens6":"https://cdn.images.express.co.uk/img/dynamic/143/590x/913231_1.jpg",
    },
    {
      "id":5,
      "name":"Gta Trilogy / Grand Theft Auto Trilogy",
      "image":"https://media-rockstargames-com.akamaized.net/rockstargames-newsite/img/global/games/fob/640/GTATrilogy.jpg",
      "secondImage":"https://wallpapercave.com/wp/wp10151632.jpg",
      "title":"THREE ICONIC CITIES,THREE EPIC STORIES",
      "description":"Play the genre-defining classics of the original Grand Theft Auto Trilogy: Grand Theft Auto III, Grand Theft Auto: Vice City, and Grand Theft Auto: San Andreas updated for a new generation, now with across-the-board enhancements including brilliant new lighting and environmental upgrades, with high-resolution textures, increased draw distances, Grand Theft Auto V-style controls and targeting, and much more, bringing these beloved worlds to life with all new levels of detail.",
      "screens":"https://alta.ge/images/detailed/288/129517_2.jpg",
      "screens2":"https://cdn.vox-cdn.com/thumbor/J-E4mUDhOonr3qivnyN4Gz44-08=/0x0:3840x2010/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/22947287/GTA_Trilogy___Definitive_Edition___GTA_III___Screen_2.jpg",
      "screens3":"https://osiris.gamefront.com/gamefront//screenshots/76f5ffa5-ed94-4775-b5ba-0b0e3c420248/GNz1j8wIo5MymTC7PAxEEuhRg2q595G9z61g5GmG.jpg?v=320",
      "screens4":"https://assets-prd.ignimgs.com/2021/10/22/gta-trilogy-1634906332402.jpg",
      "screens5":"https://www.insidesport.in/wp-content/uploads/2021/12/gta_trilogy_1.jpg",
      "screens6":"https://storage.googleapis.com/stateless-gstylemag-com/2021/11/Grand-Theft-Auto_-Vice-City-%E2%80%93-The-Definitive-Edition_20211127230008.jpg",
    },
    {
      "id":6,
      "name":"Gta: San Andreas / Grand Theft Auto: San Andreas / Gta San Andreas / Grand Theft Auto San Andreas",
      "image":"https://media-rockstargames-com.akamaized.net/rockstargames-newsite/img/global/games/fob/640/sanandreas.jpg",
      // "secondImage":"https://media.moddb.com/images/mods/1/56/55245/GTA_SanAndreas_Artwork_Title_Wal.jpg",
      "secondImage":"https://freepngimg.com/thumb/gta/28666-6-gta-san-andreas-photo.png",
      "title":"Grand Theft Auto: San Andreas",
      "description":"Five years ago Carl Johnson escaped from the pressures of life in Los Santos, San Andreas — a city tearing itself apart with gang trouble, drugs, and corruption. Where film stars and millionaires do their best to avoid the dealers and gangbangers. Now, it's the early '90s. Carl's got to go home. His mother has been murdered, his family has fallen apart and his childhood friends are all heading toward disaster. On his return to the neighborhood, a couple of corrupt cops frame him for homicide. CJ is forced on a journey that takes him across the entire state of San Andreas, to save his family and to take control of the streets.",
      "screens":"https://gamehay.io/images/Grand-Theft-Auto.webp",
      "screens2":"https://coolwallpapers.me/picsup/5510028-grand-theft-auto-san-andreas-hd-wallpapers.jpg",
      "screens3":"https://media-rockstargames-com.akamaized.net/rockstargames-newsite/img/global/games/screens/31-1.jpg",
      "screens4":"https://media-rockstargames-com.akamaized.net/rockstargames-newsite/img/global/games/screens/31-3.jpg",
      "screens5":"https://media-rockstargames-com.akamaized.net/rockstargames-newsite/img/global/games/screens/31-2.jpg",
      "screens6":"https://media-rockstargames-com.akamaized.net/rockstargames-newsite/img/global/games/screens/31-4.jpg",
    },
    {
      "id":7,
      "name":"Gta 4 / Grand Theft Auto 4",
      "image":"https://media-rockstargames-com.akamaized.net/rockstargames-newsite/img/global/games/fob/640/IV.jpg",
      "secondImage":"https://cdn.wccftech.com/wp-content/uploads/2021/11/Grand-Theft-Auto-IV-Remastered.jpg",
      "title":"Grand Theft Auto 4",
      "description":"What does the American Dream mean today? For Niko Bellic, fresh off the boat from Europe, it is the hope he can escape his past. For his cousin, Roman, it is the vision that together they can find fortune in Liberty City, gateway to the land of opportunity.",
      "screens":"https://external-preview.redd.it/a8EbMcn6BZQkDohMnNGET8nzEYu06OnXW5Rkutw6m5k.png?auto=webp&s=1ae08ee714509646602b554a5e04c545d28feb35",
      "screens2":"https://fraghero.com/wp-content/uploads/2016/11/gta4.jpg",
      "screens3":"https://assetsio.reedpopcdn.com/3447_gta_iv_trailer.jpg.jpg?width=1600&height=900&fit=crop&quality=100&format=png&enable=upscale&auto=webp",
      "screens4":"https://gamefa.com/wp-content/uploads/2018/04/19-GTA-IV-ds1-670x377-constrain.jpg",
      "screens5":"https://media.gtanet.com/images/4283-gta-iv-gtanet-exclusive-screenshot.jpg",
      "screens6":"https://media-cldnry.s-nbcnews.com/image/upload/t_fit-760w,f_auto,q_auto:best/msnbc/Components/Photo_StoryLevel/080514/080514-gta4-2-hlarg-5p.jpg",
    },
    {
      "id":8,
      "name":"Bully Scholarship",
      "image":"https://media-rockstargames-com.akamaized.net/rockstargames-newsite/img/global/games/fob/640/bully.jpg",
      "secondImage":"https://www.rollingstone.com/wp-content/uploads/2018/06/bully-1401x788-26f2fb1b-5811-46e5-8c81-7a84e55e443d.png?w=1401&h=788&crop=1",
      "title":"Bully Scholarship",
      "description":"The Rockstar tradition of groundbreaking, original gameplay and humorous tongue-in-cheek storytelling invades an entirely new setting: the schoolyard. As a mischievous schoolboy, you'll stand up to bullies, get picked on by teachers, play pranks, win or lose the girl, and ultimately learn to navigate the obstacles of the worst school around, Bullworth Academy — a corrupt and crumbling prep school with an uptight facade.",
      "screens":"https://cdn.cloudflare.steamstatic.com/steam/apps/12200/0000006052.1920x1080.jpg?t=1695140211",
      "screens2":"https://cdn.dreamgame.com/assets/images/thumbs/6160e64d871f057c80fc06c7-bully-scholarship-edition-400.jpeg",
      "screens3":"https://gpstatic.com/acache/27/31/1/us/s3-6a06ed5b7c45ea05a23119167d1cc4f9.jpg",
      "screens4":"https://gpstatic.com/acache/27/31/1/us/s7-fd0e1d9cb0393d2c96cc945bfb3fa5a7.jpg",
      "screens5":"https://gpstatic.com/acache/27/31/1/us/s6-5d54497455f8f0ca866ceaef84e0e6f3.jpg",
      "screens6":"https://gpstatic.com/acache/27/31/1/us/s10-8326350d078e3edf8896cf66be2f4ae3.jpg",
    },
    {
      "id":9,
      "name":"Gta 4: Episodes From Liberty City / Grand Theft Auto 4: Episodes From Liberty City",
      "image":"https://media-rockstargames-com.akamaized.net/rockstargames-newsite/img/global/games/fob/640/episodesfromlibertycity.jpg",
      "secondImage":"https://media-rockstargames-com.akamaized.net/rockstargames-newsite/img/global/games/fob/640/episodesfromlibertycity.jpg",
      "title":"Grand Theft Auto 4: Episodes From Liberty City",
      "description":"Liberty City worships money and status — it's heaven for those who have them, and a living nightmare for those who don't. Johnny, a veteran member of The Lost biker gang, is caught in the middle of a vicious turf war with rival gangs for control of the city. Luis, part-time hoodlum and full-time assistant to legendary nightclub impresario Tony Prince (a.k.a. “Gay Tony”), is struggling with the competing loyalties of family and friends in a world in which everyone has a price. Their lives cross paths with devastating consequences as they fight to survive in a city torn apart by violence and corruption.",
      "screens":"https://rukminim2.flixcart.com/image/850/1000/jlqwpe80-1/physical-game/4/g/n/standard-edition-grand-theft-auto-episodes-from-liberty-city-original-imaf8npcnqascxhr.jpeg?q=90",
      "screens2":"https://cdn.cloudflare.steamstatic.com/steam/apps/12220/ss_18af911406ddb3ee80f1fd17ebf6e274bf7efcbc.1920x1080.jpg?t=1618853641",
      "screens3":"https://cdn.cloudflare.steamstatic.com/steam/apps/12220/ss_1c64a2bceb9ffbadda97fc355a2821bc13005f54.1920x1080.jpg?t=1618853641",
      "screens4":"https://images.sftcdn.net/images/t_app-cover-l,f_auto/p/0980efaa-9b35-11e6-9543-00163ec9f5fa/833574097/grand-theft-auto-episodes-from-liberty-city-screenshot.jpg",
      "screens5":"https://images.sftcdn.net/images/t_app-cover-l,f_auto/p/0980efaa-9b35-11e6-9543-00163ec9f5fa/1115266516/grand-theft-auto-episodes-from-liberty-city-screenshot.jpg",
      "screens6":"https://s3.amazonaws.com/prod-media.gameinformer.com/styles/thumbnail/s3/legacy-images/Rockstar%20Sends%20GTA%20IV%20Off%20In%20Fabulous%20Style/7455.RSG_5F00_TBoGT_5F00_Screenshot_5F00_083.jpg",
    },
  ]
};

export default (req, res) => {
  res.status(200).json(featuredGamesData);
};
